# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "* 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub tokebn
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ignazio-bovo
          template: classic
          filename: github-metrics.svg
          base: header, activity, community, repositories
          plugin_lines: yes
